"""
Data schemas and type definitions for SatQuery-AI Module 5 (M5) integration.
Provides structured contracts for inputs from upstream AI modules (M2/M3)
and outputs generated by the M5 geospatial engine.
"""

import json
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any


@dataclass
class M2M3Payload:
    """
    Standardized payload schema received from upstream AI detection modules (M2/M3).

    Attributes:
        target: Target classification name (e.g. 'new building', 'deforestation', 'vehicle').
        confidence: Model prediction confidence score (0.0 to 1.0).
        change_detected: Boolean flag indicating if change or target was identified.
        reference_image: Path to the reference GeoTIFF satellite image.
        change_mask: Optional path to binary change mask (.npy or raster) or ndarray.
        bounding_boxes: Optional list of pixel bounding boxes [[xmin, ymin, xmax, ymax], ...].
        metadata: Optional dictionary for additional upstream model metadata.
    """
    target: str = "detected_change"
    confidence: float = 0.85
    change_detected: bool = True
    reference_image: str = ""
    change_mask: str | Any | None = None
    bounding_boxes: list[list[float]] | None = field(default_factory=list)
    metadata: dict[str, Any] | None = field(default_factory=dict)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "M2M3Payload":
        """
        Create an M2M3Payload instance from a dictionary.
        Supports standard and legacy/alias field names for maximum team compatibility:
            - reference_image or reference_geotiff
            - change_mask or change_mask_path
            - bounding_boxes or bounding_boxes_pixel
        """
        ref_img = data.get("reference_image") or data.get("reference_geotiff") or ""
        mask = data.get("change_mask") if "change_mask" in data else data.get("change_mask_path")
        bboxes = data.get("bounding_boxes") if "bounding_boxes" in data else data.get("bounding_boxes_pixel")

        return cls(
            target=str(data.get("target", "detected_change")),
            confidence=float(data.get("confidence", 0.85)),
            change_detected=bool(data.get("change_detected", True)),
            reference_image=str(ref_img),
            change_mask=mask,
            bounding_boxes=bboxes or [],
            metadata=data.get("metadata", {}),
        )

    @classmethod
    def from_json(cls, json_str_or_path: str | Path) -> "M2M3Payload":
        """Load an M2M3Payload from a JSON string or file path."""
        path = Path(json_str_or_path)
        if path.is_file():
            with open(path, "r", encoding="utf-8") as f:
                data = json.load(f)
        else:
            data = json.loads(str(json_str_or_path))
        return cls.from_dict(data)

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary representation."""
        return asdict(self)


@dataclass
class EvidenceOutput:
    """
    Standardized schema for M5 output artifacts and evidence metrics.
    """
    target: str
    confidence: float
    change_detected: bool
    bounding_boxes: list[dict[str, Any]]
    geographic_coordinates: dict[str, Any]
    polygons: list[dict[str, Any]]
    area: dict[str, Any]
    evidence_path: str
    geojson_path: str
    map_path: str
    raster_metadata: dict[str, Any] | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "EvidenceOutput":
        return cls(
            target=data["target"],
            confidence=data["confidence"],
            change_detected=data["change_detected"],
            bounding_boxes=data.get("bounding_boxes", []),
            geographic_coordinates=data.get("geographic_coordinates", {}),
            polygons=data.get("polygons", []),
            area=data.get("area", {}),
            evidence_path=data.get("evidence_path", ""),
            geojson_path=data.get("geojson_path", ""),
            map_path=data.get("map_path", ""),
            raster_metadata=data.get("raster_metadata"),
        )

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)
