"""
SatQuery AI - M4 Query Schemas

Defines the structured data contracts used by the M4
agentic controller.

Pipeline:

    User Query
        ↓
    QueryRequest
        ↓
    ParsedQuery
        ↓
    ExecutionPlan
        ↓
    ToolResult
        ↓
    AgentResponse
"""

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------

class Intent(str, Enum):
    """High-level user intents supported by SatQuery."""

    VQA = "VQA"
    CHANGE_DETECTION = "CHANGE_DETECTION"
    GROUNDING = "GROUNDING"
    OPTICAL_SAR = "OPTICAL_SAR"


class Operation(str, Enum):
    """Specific operation requested by the user."""

    DESCRIBE = "describe"
    ANSWER = "answer"
    DETECT_CHANGE = "detect_change"
    DETECT_NEW = "detect_new"
    LOCALIZE = "localize"
    ANALYZE = "analyze"


class ToolName(str, Enum):
    """
    Specialist tools available to the M4 controller.

    M1 -> VQA
    M2 -> Change Detection / Grounding
    M3 -> Optical + SAR
    M5 -> GIS
    """

    M1_VQA = "m1_vqa"
    M2_CHANGE_DETECTION = "m2_change_detection"
    M2_GROUNDING = "m2_grounding"
    M3_OPTICAL_SAR = "m3_optical_sar"
    M5_GIS = "m5_gis"


class ExecutionStatus(str, Enum):
    """Execution state of a tool or the complete agent."""

    SUCCESS = "success"
    FAILED = "failed"
    PARTIAL = "partial"


# ---------------------------------------------------------------------------
# Input schema
# ---------------------------------------------------------------------------

class QueryRequest(BaseModel):
    """
    Raw request received by M4 from the application/frontend.
    """

    query: str = Field(
        ...,
        min_length=1,
        description="Natural-language satellite query.",
    )

    images: list[str] = Field(
        default_factory=list,
        description="Paths or identifiers of satellite images.",
    )

    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Optional request metadata.",
    )


# ---------------------------------------------------------------------------
# Parsed query schema
# ---------------------------------------------------------------------------

class ParsedQuery(BaseModel):
    """
    Structured representation of the user's natural-language query.

    Produced by the query parser and consumed by the classifier/planner.
    """

    original_query: str

    intent: Intent

    operation: Operation

    target: str | None = None

    temporal: bool = False

    requires_grounding: bool = False

    requires_geospatial: bool = False

    modalities: list[str] = Field(
        default_factory=list,
        description="Input modalities such as optical or SAR.",
    )

    entities: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional extracted query parameters.",
    )


# ---------------------------------------------------------------------------
# Execution plan schemas
# ---------------------------------------------------------------------------

class PlanStep(BaseModel):
    """Represents one executable step in the M4 plan."""

    step_id: int = Field(
        ...,
        ge=1,
        description="One-based execution step number.",
    )

    tool: ToolName

    operation: str

    inputs: list[str] = Field(
        default_factory=list,
        description="Input references required by the tool.",
    )

    parameters: dict[str, Any] = Field(
        default_factory=dict,
        description="Tool-specific execution parameters.",
    )


class ExecutionPlan(BaseModel):
    """Complete execution plan generated by M4."""

    intent: Intent

    steps: list[PlanStep] = Field(
        ...,
        min_length=1,
    )


# ---------------------------------------------------------------------------
# Evidence schema
# ---------------------------------------------------------------------------

class Evidence(BaseModel):
    """
    Represents one piece of evidence produced during analysis.

    Examples:
        - change mask
        - image overlay
        - bounding box
        - GIS polygon
        - geographic coordinates
        - statistics
    """

    type: str

    reference: str | None = None

    description: str | None = None

    metadata: dict[str, Any] = Field(
        default_factory=dict,
    )


# ---------------------------------------------------------------------------
# Tool result schema
# ---------------------------------------------------------------------------

class ToolResult(BaseModel):
    """
    Standardized result returned by M1, M2, M3, or M5.
    """

    tool: ToolName

    status: ExecutionStatus

    confidence: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
    )

    data: dict[str, Any] = Field(
        default_factory=dict,
    )

    evidence: list[Evidence] = Field(
        default_factory=list,
    )

    error: str | None = None


# ---------------------------------------------------------------------------
# Final agent response
# ---------------------------------------------------------------------------

class AgentResponse(BaseModel):
    """
    Final structured response returned by M4 to M6.

    The frontend should consume this object rather than depending
    directly on M1/M2/M3/M5 implementation details.
    """

    status: ExecutionStatus

    answer: str

    confidence: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
    )

    intent: Intent

    evidence: list[Evidence] = Field(
        default_factory=list,
    )

    results: list[ToolResult] = Field(
        default_factory=list,
    )

    trace: list[str] = Field(
        default_factory=list,
    )

    error: str | None = None
