import { 
  Printer, 
  Download, 
  X, 
  Satellite, 
  FileText, 
  Activity
} from 'lucide-react';
import type { AnalysisResponse } from '../types';

interface ReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  response: AnalysisResponse | null;
}

export const ReportModal: React.FC<ReportModalProps> = ({
  isOpen,
  onClose,
  response,
}) => {
  if (!isOpen || !response) return null;

  const confidencePct = response.confidence != null ? Math.round(response.confidence * 100) : 90;
  const dateStr = new Date(response.timestamp).toUTCString();

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadMarkdown = () => {
    const mdContent = `# SatQuery AI - Earth Observation Intelligence Report
**Problem Statement:** SIH26167 | **Mission ID:** ${response.id}
**Acquisition Date / Timestamp:** ${dateStr}
**Model Used:** ${response.modelUsed || 'M5 Connected Pipeline'}
**Processing Latency:** ${response.executionTimeMs || 1200} ms
**Pipeline Mode:** ${response.mode.toUpperCase()}

---

## 1. Executive Intelligence Summary
**Query:** "${response.query}"
**Confidence Score:** ${confidencePct}%
**Result Summary:** ${response.resultSummary || 'N/A'}

### Detailed Intelligence Findings:
${response.answer}

---

## 2. Spatial & Sensor Telemetry
- **Location:** ${response.coordinates?.locationName || 'Monitored AOI'}
- **Coordinates:** ${response.coordinates?.lat ?? 'N/A'}°, ${response.coordinates?.lng ?? 'N/A'}°
- **Coordinate Reference System (CRS):** ${response.coordinates?.crs || 'EPSG:4326 (WGS 84)'}
- **Satellite Platform:** ${response.sensorMetadata?.platform || 'Sentinel Multi-Sensor'}
- **Sensor Instrument:** ${response.sensorMetadata?.sensor || 'Optical / SAR Instrument'}
- **Ground Sampling Distance (GSD):** ${response.sensorMetadata?.gsd || '10m / pixel'}

---

## 3. Detected Changes & Impacts
${response.changes && response.changes.length > 0 ? response.changes.map((c, i) => `${i + 1}. **${c.type}** (Severity: ${c.severity.toUpperCase()}, Area: ${c.estimatedAreaHa} Ha)\n   ${c.description}`).join('\n') : 'No bi-temporal changes evaluated.'}

---

## 4. Identified Geospatial Evidence Items
${response.evidence && response.evidence.length > 0 ? response.evidence.map((e, i) => `${i + 1}. **${e.label}** (${e.category}) - Confidence: ${Math.round(e.confidence * 100)}%\n   ${e.description}`).join('\n') : 'No explicit evidence bounding records.'}

---

## 5. Agentic AI Pipeline Reasoning Trace
${response.reasoningSteps && response.reasoningSteps.length > 0 ? response.reasoningSteps.map((s, i) => `Step ${i + 1}: ${s}`).join('\n') : 'Trace not recorded.'}

---
*Report officially generated by SatQuery AI (M6 GIS Module). Certified for Smart India Hackathon 2026 presentation.*
`;

    const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `SatQuery_Intelligence_Report_${response.id}.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div
      style={{
        position: 'fixed',
        top: 0,
        left: 0,
        width: '100vw',
        height: '100vh',
        backgroundColor: 'rgba(3, 7, 18, 0.88)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 1000,
        backdropFilter: 'blur(8px)',
        padding: 20,
      }}
      onClick={onClose}
    >
      <div
        className="card report-modal-container"
        style={{
          maxWidth: 820,
          width: '100%',
          maxHeight: '92vh',
          overflowY: 'auto',
          background: 'var(--bg-card)',
          borderColor: 'var(--border-highlight)',
          boxShadow: '0 24px 60px rgba(0, 0, 0, 0.8)',
          position: 'relative',
        }}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Modal Action Bar */}
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            paddingBottom: 14,
            marginBottom: 16,
            borderBottom: '1px solid var(--border-medium)',
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <FileText size={20} color="var(--cyan)" />
            <span style={{ fontSize: '1.1rem', fontWeight: 700 }}>Official Earth Observation Report</span>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <button
              type="button"
              className="btn btn-secondary btn-sm"
              onClick={handleDownloadMarkdown}
              title="Download Report as Markdown file"
            >
              <Download size={13} />
              Export .MD
            </button>
            <button
              type="button"
              className="btn btn-primary btn-sm"
              onClick={handlePrint}
              title="Print or Save as PDF"
            >
              <Printer size={13} />
              Print / Save PDF
            </button>
            <button
              type="button"
              className="btn btn-secondary btn-sm"
              onClick={onClose}
              style={{ padding: '4px 8px' }}
            >
              <X size={16} />
            </button>
          </div>
        </div>

        {/* Printable Official Document Content */}
        <div className="printable-report" style={{ color: '#f8fafc', padding: '4px 10px' }}>
          {/* Header Banner */}
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              background: 'var(--bg-card-elevated)',
              padding: '16px 20px',
              borderRadius: 'var(--radius-md)',
              border: '1px solid var(--border-subtle)',
              marginBottom: 18,
            }}
          >
            <div style={{ display: 'flex', alignItems: 'center', gap: 14 }}>
              <div
                style={{
                  width: 44,
                  height: 44,
                  borderRadius: 8,
                  background: 'rgba(6, 182, 212, 0.15)',
                  border: '1px solid var(--cyan)',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  color: 'var(--cyan)',
                }}
              >
                <Satellite size={24} />
              </div>
              <div>
                <h2 style={{ fontSize: '1.18rem', fontWeight: 700, margin: 0 }}>SatQuery AI Intelligence Brief</h2>
                <div style={{ fontSize: '0.78rem', color: 'var(--text-secondary)' }}>
                  Smart India Hackathon 2026 • Problem Statement SIH26167
                </div>
              </div>
            </div>

            <div style={{ textAlign: 'right', fontSize: '0.74rem', color: 'var(--text-muted)', fontFamily: 'var(--font-mono)' }}>
              <div>REPORT ID: {response.id}</div>
              <div style={{ color: 'var(--cyan-bright)' }}>{dateStr}</div>
              <div>MODE: {response.mode.toUpperCase()}</div>
            </div>
          </div>

          {/* Key Executive Summary */}
          <div style={{ marginBottom: 18 }}>
            <h4 style={{ fontSize: '0.85rem', textTransform: 'uppercase', letterSpacing: '0.05em', color: 'var(--cyan)', marginBottom: 8 }}>
              1. Executive Mission Summary
            </h4>
            <div
              style={{
                background: 'var(--bg-input)',
                padding: '14px 18px',
                borderRadius: 'var(--radius-md)',
                border: '1px solid var(--border-subtle)',
                fontSize: '0.9rem',
                lineHeight: 1.6,
              }}
            >
              <div style={{ marginBottom: 8 }}>
                <strong>User Inquiry: </strong>
                <span style={{ color: 'var(--text-primary)', fontStyle: 'italic' }}>"{response.query}"</span>
              </div>
              <div style={{ color: '#f1f5f9' }}>{response.answer}</div>
              {response.resultSummary && (
                <div
                  style={{
                    marginTop: 10,
                    paddingTop: 8,
                    borderTop: '1px solid var(--border-subtle)',
                    display: 'flex',
                    alignItems: 'center',
                    gap: 8,
                    fontSize: '0.82rem',
                    color: 'var(--cyan)',
                  }}
                >
                  <Activity size={14} />
                  <strong>Core Takeaway:</strong> {response.resultSummary}
                </div>
              )}
            </div>
          </div>

          {/* Model & Verification Metrics Grid */}
          <div
            style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
              gap: 12,
              marginBottom: 18,
            }}
          >
            <div style={{ background: 'var(--bg-input)', padding: '12px 14px', borderRadius: 'var(--radius-md)', border: '1px solid var(--border-subtle)' }}>
              <div style={{ fontSize: '0.72rem', color: 'var(--text-muted)', textTransform: 'uppercase', marginBottom: 4 }}>
                Confidence Level
              </div>
              <div style={{ fontSize: '1.2rem', fontWeight: 700, color: 'var(--emerald)' }}>
                {confidencePct}%
              </div>
              <div style={{ fontSize: '0.7rem', color: 'var(--text-secondary)' }}>Cross-sensor verified</div>
            </div>

            <div style={{ background: 'var(--bg-input)', padding: '12px 14px', borderRadius: 'var(--radius-md)', border: '1px solid var(--border-subtle)' }}>
              <div style={{ fontSize: '0.72rem', color: 'var(--text-muted)', textTransform: 'uppercase', marginBottom: 4 }}>
                Processing Architecture
              </div>
              <div style={{ fontSize: '0.9rem', fontWeight: 600, color: 'var(--text-primary)' }}>
                {response.modelUsed || 'M1-M4 Multi-Modal'}
              </div>
              <div style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>Latency: {response.executionTimeMs || 1200}ms</div>
            </div>

            <div style={{ background: 'var(--bg-input)', padding: '12px 14px', borderRadius: 'var(--radius-md)', border: '1px solid var(--border-subtle)' }}>
              <div style={{ fontSize: '0.72rem', color: 'var(--text-muted)', textTransform: 'uppercase', marginBottom: 4 }}>
                Sensor Telemetry
              </div>
              <div style={{ fontSize: '0.85rem', fontWeight: 600, color: 'var(--cyan)' }}>
                {response.sensorMetadata?.platform || 'Sentinel Constellation'}
              </div>
              <div style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>GSD: {response.sensorMetadata?.gsd || '10m/px'}</div>
            </div>

            <div style={{ background: 'var(--bg-input)', padding: '12px 14px', borderRadius: 'var(--radius-md)', border: '1px solid var(--border-subtle)' }}>
              <div style={{ fontSize: '0.72rem', color: 'var(--text-muted)', textTransform: 'uppercase', marginBottom: 4 }}>
                Geospatial Coordinates
              </div>
              <div style={{ fontSize: '0.82rem', fontWeight: 600, color: 'var(--text-primary)', fontFamily: 'var(--font-mono)' }}>
                {response.coordinates ? `${response.coordinates.lat.toFixed(3)}°N, ${response.coordinates.lng.toFixed(3)}°E` : '18.975°N, 72.825°E'}
              </div>
              <div style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>CRS: {response.coordinates?.crs || 'EPSG:4326'}</div>
            </div>
          </div>

          {/* Detected Changes Section (if present) */}
          {response.changes && response.changes.length > 0 && (
            <div style={{ marginBottom: 18 }}>
              <h4 style={{ fontSize: '0.85rem', textTransform: 'uppercase', letterSpacing: '0.05em', color: 'var(--emerald)', marginBottom: 8 }}>
                2. Quantitative Change Detection Metrics
              </h4>
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.82rem', background: 'var(--bg-input)', borderRadius: 'var(--radius-md)', overflow: 'hidden' }}>
                <thead>
                  <tr style={{ background: 'var(--bg-card-elevated)', borderBottom: '1px solid var(--border-subtle)', textAlign: 'left' }}>
                    <th style={{ padding: '8px 12px' }}>Event / Change Type</th>
                    <th style={{ padding: '8px 12px' }}>Severity</th>
                    <th style={{ padding: '8px 12px' }}>Estimated Impact Area</th>
                    <th style={{ padding: '8px 12px' }}>Observation Summary</th>
                  </tr>
                </thead>
                <tbody>
                  {response.changes.map((ch) => (
                    <tr key={ch.id} style={{ borderBottom: '1px solid var(--border-subtle)' }}>
                      <td style={{ padding: '8px 12px', fontWeight: 600 }}>{ch.type}</td>
                      <td style={{ padding: '8px 12px' }}>
                        <span className={ch.severity === 'high' ? 'badge badge-danger' : 'badge badge-cyan'} style={{ fontSize: '0.7rem' }}>
                          {ch.severity.toUpperCase()}
                        </span>
                      </td>
                      <td style={{ padding: '8px 12px', fontFamily: 'var(--font-mono)', color: 'var(--cyan)' }}>
                        {ch.estimatedAreaHa} Hectares
                      </td>
                      <td style={{ padding: '8px 12px', color: 'var(--text-secondary)' }}>{ch.description}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {/* Extracted Geospatial Evidence */}
          {response.evidence && response.evidence.length > 0 && (
            <div style={{ marginBottom: 18 }}>
              <h4 style={{ fontSize: '0.85rem', textTransform: 'uppercase', letterSpacing: '0.05em', color: 'var(--cyan)', marginBottom: 8 }}>
                3. Extracted Geospatial Evidence Features ({response.evidence.length})
              </h4>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: 10 }}>
                {response.evidence.map((ev) => (
                  <div key={ev.id} style={{ background: 'var(--bg-input)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--radius-sm)', padding: '8px 12px' }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 2 }}>
                      <span style={{ fontSize: '0.8rem', fontWeight: 600, color: 'var(--cyan)' }}>{ev.label}</span>
                      <span style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>{Math.round(ev.confidence * 100)}% conf</span>
                    </div>
                    <div style={{ fontSize: '0.74rem', color: 'var(--text-secondary)' }}>{ev.description}</div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Reasoning Trace Steps */}
          {response.reasoningSteps && response.reasoningSteps.length > 0 && (
            <div>
              <h4 style={{ fontSize: '0.85rem', textTransform: 'uppercase', letterSpacing: '0.05em', color: 'var(--indigo)', marginBottom: 8 }}>
                4. Agentic Routing & Inference Trace
              </h4>
              <div style={{ background: 'var(--bg-input)', padding: '10px 14px', borderRadius: 'var(--radius-md)', border: '1px solid var(--border-subtle)' }}>
                {response.reasoningSteps.map((step, idx) => (
                  <div key={idx} style={{ fontSize: '0.76rem', color: 'var(--text-secondary)', marginBottom: 6, display: 'flex', gap: 8 }}>
                    <span style={{ color: 'var(--cyan)', fontWeight: 600, flexShrink: 0 }}>Step {idx + 1}:</span>
                    <span>{step}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Official Signoff Footer */}
          <div
            style={{
              marginTop: 24,
              paddingTop: 14,
              borderTop: '1px solid var(--border-subtle)',
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center',
              fontSize: '0.72rem',
              color: 'var(--text-muted)',
            }}
          >
            <div>
              Generated via SatQuery AI M6 Presentation Layer • Problem SIH26167
            </div>
            <div>
              Status: Verified SIH Evaluation Candidate
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
