"""
M4 adapter for the native M5 GIS / geospatial subsystem.

Architecture:

    M4 ToolResult from M2/M3
            |
            v
    M2M3Payload normalization
            |
            v
    process_m2_m3_result()
            |
            v
    Native M5 evidence dictionary
            |
            v
        M4 ToolResult

M4 owns the stable ToolResult contract.
M5 owns the native geospatial implementation.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from app.adapters.common import convert_tool_output
from app.query.schemas import (
    Evidence,
    ExecutionStatus,
    ToolName,
    ToolResult,
)

from geospatial.integration import process_m2_m3_result
from geospatial.schema import M2M3Payload


def _first_value(*values: Any) -> Any:
    """Return the first non-empty value."""
    for value in values:
        if value is not None and value != "":
            return value
    return None


def _extract_native_dict(result: ToolResult) -> dict[str, Any]:
    """
    Extract the specialist-native payload from an M4 ToolResult.

    M2 and M3 intentionally preserve their complete native result
    inside ToolResult.data, so M5 can consume that information
    without coupling itself to M2/M3 internals.
    """
    data = result.data or {}

    # M3 explicitly preserves its complete native result here.
    m3 = data.get("m3")
    if isinstance(m3, dict):
        return {
            **data,
            **m3,
        }

    # M2 keeps its native evidence/artifacts in data.
    return data


def _extract_m5_payload(
    previous_result: ToolResult,
    target: str | None = None,
) -> M2M3Payload:
    """
    Convert an upstream M2/M3 ToolResult into the native M5 payload.

    No synthetic image paths are created. M5 requires a real reference
    raster, therefore absence of a usable reference image is reported
    explicitly.
    """

    if not isinstance(previous_result, ToolResult):
        raise TypeError(
            "M5 requires previous_result to be an M4 ToolResult."
        )

    if previous_result.status == ExecutionStatus.FAILED:
        raise ValueError(
            "M5 cannot process a failed upstream specialist result."
        )

    native = _extract_native_dict(previous_result)
    data = previous_result.data or {}

    metadata: dict[str, Any] = {
        "upstream_tool": previous_result.tool.value,
        "upstream_status": previous_result.status.value,
        "upstream_data": data,
    }

    # ---------------------------------------------------------
    # Reference image
    # ---------------------------------------------------------

    reference_image = _first_value(
        native.get("reference_image"),
        native.get("reference_geotiff"),
        native.get("reference_image_path"),
        native.get("reference_geotiff_path"),
        data.get("reference_image"),
        data.get("reference_geotiff"),
    )

    # M2 artifacts may contain paths generated by the native
    # change-detection pipeline.
    artifacts = native.get("artifacts", [])

    if isinstance(artifacts, list):
        for artifact in artifacts:
            if isinstance(artifact, dict):
                reference_image = _first_value(
                    reference_image,
                    artifact.get("reference_image"),
                    artifact.get("reference_geotiff"),
                    artifact.get("path")
                    if artifact.get("type") in {
                        "reference_image",
                        "reference_geotiff",
                    }
                    else None,
                )

    # M3 may expose optical metadata/path information.
    optical = native.get("optical", {})
    if isinstance(optical, dict):
        reference_image = _first_value(
            reference_image,
            optical.get("path"),
            optical.get("image_path"),
            optical.get("source"),
        )

    # ---------------------------------------------------------
    # Change mask
    # ---------------------------------------------------------

    change_mask = _first_value(
        native.get("change_mask"),
        native.get("change_mask_path"),
        data.get("change_mask"),
        data.get("change_mask_path"),
    )

    if isinstance(artifacts, list):
        for artifact in artifacts:
            if isinstance(artifact, dict):
                artifact_type = str(
                    artifact.get("type", "")
                ).lower()

                if "mask" in artifact_type:
                    change_mask = _first_value(
                        change_mask,
                        artifact.get("path"),
                        artifact.get("change_mask"),
                        artifact.get("change_mask_path"),
                    )

    # ---------------------------------------------------------
    # Bounding boxes
    # ---------------------------------------------------------

    bounding_boxes = _first_value(
        native.get("bounding_boxes"),
        native.get("bounding_boxes_pixel"),
        data.get("bounding_boxes"),
        data.get("bounding_boxes_pixel"),
    )

    if not isinstance(bounding_boxes, list):
        bounding_boxes = []

    # ---------------------------------------------------------
    # Target
    # ---------------------------------------------------------

    resolved_target = _first_value(
        target,
        native.get("target"),
        native.get("class_name"),
        native.get("predicted_class_name"),
        native.get("predicted_class"),
        data.get("target"),
    )

    if resolved_target is None:
        resolved_target = "detected_change"

    # ---------------------------------------------------------
    # Confidence
    # ---------------------------------------------------------

    confidence = previous_result.confidence

    # M3 preserves its native confidence structure.
    native_confidence = native.get("confidence")

    if isinstance(native_confidence, dict):
        score = native_confidence.get("score")
        if score is not None:
            confidence = float(score)

    elif isinstance(native_confidence, (int, float)):
        confidence = float(native_confidence)

    confidence = max(0.0, min(1.0, float(confidence)))

    # ---------------------------------------------------------
    # Change flag
    # ---------------------------------------------------------

    change_detected = _first_value(
        native.get("change_detected"),
        data.get("change_detected"),
    )

    if change_detected is None:
        # M2 change detection reaching M5 means a detected result.
        if previous_result.tool == ToolName.M2_CHANGE_DETECTION:
            change_detected = True
        else:
            change_detected = bool(
                change_mask or bounding_boxes
            )

    metadata.update(
        {
            "native_result": native,
            "source_tool": previous_result.tool.value,
        }
    )

    if not reference_image:
        raise ValueError(
            "M5 requires a reference GeoTIFF path from the upstream "
            "M2/M3 ToolResult, but none was provided."
        )

    return M2M3Payload(
        target=str(resolved_target),
        confidence=confidence,
        change_detected=bool(change_detected),
        reference_image=str(reference_image),
        change_mask=change_mask,
        bounding_boxes=bounding_boxes,
        metadata=metadata,
    )


def _convert_m5_output(
    raw_output: dict[str, Any],
) -> ToolResult:
    """
    Convert native M5 evidence dictionary into M4 ToolResult.
    """

    if not isinstance(raw_output, dict):
        raise TypeError(
            "Native M5 pipeline must return a dictionary."
        )

    confidence = float(
        raw_output.get("confidence", 0.0)
    )

    status = (
        ExecutionStatus.SUCCESS
        if raw_output.get("change_detected", False)
        else ExecutionStatus.PARTIAL
    )

    target = raw_output.get(
        "target",
        "detected_change",
    )

    data: dict[str, Any] = {
        "answer": (
            f"Geospatial analysis completed for '{target}'."
        ),
        "task": "gis_geospatial_analysis",
        "model": "M5-GIS",
        "native_status": "success",
        "target": target,
        "change_detected": raw_output.get(
            "change_detected",
            False,
        ),
        "geographic_coordinates": raw_output.get(
            "geographic_coordinates",
            {},
        ),
        "bounding_boxes": raw_output.get(
            "bounding_boxes",
            [],
        ),
        "polygons": raw_output.get(
            "polygons",
            [],
        ),
        "area": raw_output.get(
            "area",
            {},
        ),
        "evidence_path": raw_output.get(
            "evidence_path",
            "",
        ),
        "geojson_path": raw_output.get(
            "geojson_path",
            "",
        ),
        "map_path": raw_output.get(
            "map_path",
            "",
        ),
        "raster_metadata": raw_output.get(
            "raster_metadata",
        ),
        # Preserve complete native M5 result.
        "m5": raw_output,
    }

    evidence: list[Evidence] = [
        Evidence(
            type="geospatial_analysis",
            reference="m5_geospatial_pipeline",
            description=(
                "Native M5 GIS geospatial processing "
                "and evidence generation."
            ),
        )
    ]

    if raw_output.get("geojson_path"):
        evidence.append(
            Evidence(
                type="geojson",
                reference=str(
                    raw_output["geojson_path"]
                ),
                description=(
                    "Generated geospatial evidence "
                    "GeoJSON artifact."
                ),
            )
        )

    if raw_output.get("map_path"):
        evidence.append(
            Evidence(
                type="interactive_map",
                reference=str(
                    raw_output["map_path"]
                ),
                description=(
                    "Generated interactive GIS map artifact."
                ),
            )
        )

    if raw_output.get("evidence_path"):
        evidence.append(
            Evidence(
                type="evidence_json",
                reference=str(
                    raw_output["evidence_path"]
                ),
                description=(
                    "Generated structured M5 evidence artifact."
                ),
            )
        )

    return ToolResult(
        tool=ToolName.M5_GIS,
        status=status,
        confidence=confidence,
        data=data,
        evidence=evidence,
        error=None,
    )


def adapt_m5_gis_output(
    raw_output: Any,
) -> ToolResult:
    """
    Preserve the original generic M4-compatible adapter contract.

    This remains available for external M5 specialists and existing
    compatibility tests.
    """

    return convert_tool_output(
        raw_output,
        ToolName.M5_GIS,
    )


def make_m5_gis_adapter(
    specialist: Any | None = None,
):
    """
    Build the M4 M5 GIS adapter.

    Native M5 is the default execution path.

    If an external specialist is explicitly supplied, the original
    compatibility behavior is preserved.
    """

    def adapter(
        previous_result: ToolResult | None = None,
        target: str | None = None,
        output_dir: str | Path = "output",
        **kwargs: Any,
    ) -> ToolResult:

        # ---------------------------------------------------------
        # Native M5 execution
        # ---------------------------------------------------------

        if specialist is None:

            if previous_result is None:
                raise ValueError(
                    "M5 GIS requires previous_result from an "
                    "upstream M2/M3 specialist."
                )

            payload = _extract_m5_payload(
                previous_result,
                target=target,
            )

            raw_output = process_m2_m3_result(
                payload,
                output_dir=output_dir,
            )

            return _convert_m5_output(raw_output)

        # ---------------------------------------------------------
        # External compatibility execution
        # ---------------------------------------------------------

        raw_output = specialist(
            previous_result=previous_result,
            target=target,
            output_dir=output_dir,
            **kwargs,
        )

        return adapt_m5_gis_output(raw_output)

    return adapter
